# Generated by Django 5.1.5 on 2025-03-20 01:21

import core.model_fields
import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretid', core.model_fields.UUID7StringField(auto_created=True, default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('opaque', 'Key value pair secrets'), ('dockerconfig', 'Docker config')], default='opaque', max_length=16)),
                ('data', encrypted_model_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='infra.namespace')),
            ],
            options={
                'db_table': 'secret_store',
            },
        ),
    ]
