# Generated by Django 5.0.7 on 2024-12-30 21:07

import core.model_fields
import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k8s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretid', core.model_fields.UUID7StringField(auto_created=True, default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('opaque', 'Key value pair secret'), ('auth', 'Auth secret')], default='opaque', max_length=16)),
                ('data', encrypted_model_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('creating', 'Resource is being created'), ('updating', 'Resource is being updated'), ('deleting', 'Resource is being deleted'), ('active', 'Resource is live'), ('stopped', 'Resource is stopped'), ('error', 'Resource is in error'), ('zombie', 'Resource exists in database but in cluster'), ('orphan', 'Resource exists in cluster but not in database')], default='creating', max_length=16)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='k8s.namespace')),
            ],
            options={
                'db_table': 'secret_store',
            },
        ),
    ]
