# Generated by Django 5.0.7 on 2024-12-16 17:10

import core.model_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('keyid', core.model_fields.UUID7StringField(default=core.model_fields.generate_uuid7, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('can_write', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField(default=None, null=True)),
                ('system_use', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
