# Generated by Django 5.1.5 on 2025-03-20 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='namespaceroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='namespace',
            name='users',
            field=models.ManyToManyField(related_name='namespaces', through='infra.NamespaceRoles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volume',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.namespace'),
        ),
    ]
