# Generated by Django 5.0.7 on 2024-10-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LBEndpoint',
        ),
    ]
