# Generated by Django 5.0.7 on 2024-10-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_lbendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LBEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
            ],
            options={
                'db_table': 'endpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
