# Generated by Django 5.0.7 on 2024-07-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('value', models.GenericIPAddressField()),
                ('ttl', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'A Record',
                'verbose_name_plural': 'A Records',
                'db_table': 'a_record',
            },
        ),
        migrations.CreateModel(
            name='CNameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
                ('ttl', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CNAME Record',
                'verbose_name_plural': 'CNAME Records',
                'db_table': 'cname_record',
            },
        ),
        migrations.CreateModel(
            name='TXTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('ttl', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TXT Record',
                'verbose_name_plural': 'TXT Records',
                'db_table': 'txt_record',
            },
        ),
    ]
