# Generated by Django 5.0.7 on 2024-10-29 05:04

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'namespaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pvcs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(auto_created=True, default=uuid_utils._uuid_utils.uuid4, unique=True)),
                ('message', models.TextField()),
                ('related_link', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='k8s.namespace')),
            ],
            options={
                'db_table': 'ns_events',
            },
        ),
        migrations.CreateModel(
            name='NamespaceRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner: Full control'), ('manager', 'Manager: Read and write'), ('viewer', 'Viewer: Read only')], default='viewer', max_length=10)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace')),
            ],
            options={
                'db_table': 'namespace_roles',
            },
        ),
    ]
