# Generated by Django 5.0.7 on 2024-11-05 19:29

import core.model_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LBEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('creating', 'Resource is being created'), ('updating', 'Resource is being updated'), ('deleting', 'Resource is being deleted'), ('active', 'Resource is live'), ('stopped', 'Resource is stopped'), ('error', 'Resource is in error'), ('zombie', 'Resource exists in database but in cluster')], default='creating', max_length=16)),
            ],
            options={
                'db_table': 'lb_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'namespaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvcid', core.model_fields.UUID7StringField(auto_created=True, default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('mount_path', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pvcs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PVCContainerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.CharField(blank=True, choices=[('', 'No Access'), ('ro', 'Read Only'), ('rw', 'Read Write')], default='', max_length=2)),
                ('main', models.CharField(blank=True, choices=[('', 'No Access'), ('ro', 'Read Only'), ('rw', 'Read Write')], default='', max_length=2)),
                ('sidecar', models.CharField(blank=True, choices=[('', 'No Access'), ('ro', 'Read Only'), ('rw', 'Read Write')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', core.model_fields.UUID7StringField(auto_created=True, default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('message', models.TextField()),
                ('related_link', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='k8s.namespace')),
            ],
            options={
                'db_table': 'ns_events',
            },
        ),
        migrations.CreateModel(
            name='NamespaceRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner: Full control'), ('manager', 'Manager: Read and write'), ('viewer', 'Viewer: Read only')], default='viewer', max_length=10)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace')),
            ],
            options={
                'db_table': 'namespace_roles',
            },
        ),
    ]
