# Generated by Django 5.0.7 on 2024-08-04 04:03

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'namespaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pvcs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', encrypted_model_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ns_secrets',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('public_ip', models.IntegerField(default=0)),
                ('gpu', models.IntegerField(default=0)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='k8s.namespace')),
            ],
            options={
                'db_table': 'ns_limits',
            },
        ),
        migrations.CreateModel(
            name='NamespaceRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner: Full control'), ('manager', 'Manager: Read/Write'), ('viewer', 'Guest: Read only')], default='viewer', max_length=10)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace')),
            ],
            options={
                'db_table': 'namespace_roles',
            },
        ),
    ]
