# Generated by Django 5.0.7 on 2024-10-29 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k8s', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='namespaceroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='namespace',
            name='users',
            field=models.ManyToManyField(related_name='namespaces', through='k8s.NamespaceRoles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvc',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace'),
        ),
        migrations.AddField(
            model_name='pvc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
