# Generated by Django 5.0.7 on 2024-07-18 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k8s', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limit',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='k8s.namespace'),
        ),
        migrations.AddField(
            model_name='namespaceuser',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='k8s.namespace'),
        ),
        migrations.AddField(
            model_name='namespaceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvc',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace'),
        ),
        migrations.AddField(
            model_name='pvc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secret',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='k8s.namespace'),
        ),
    ]
