# Generated by Django 5.0.7 on 2024-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvc',
            name='size',
            field=models.FloatField(),
        ),
    ]
