# Generated by Django 5.0.7 on 2024-07-18 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NamespaceUser',
            new_name='Namespaces',
        ),
        migrations.RemoveField(
            model_name='namespace',
            name='owner',
        ),
        migrations.AlterField(
            model_name='namespace',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
