# Generated by Django 5.0.7 on 2024-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0003_rename_namespaceuser_namespaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespaces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
