# Generated by Django 5.0.7 on 2024-07-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0004_alter_namespaces_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='gpu',
            field=models.IntegerField(default=0),
        ),
    ]
