# Generated by Django 5.0.7 on 2024-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0005_limit_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespaces',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner: Full control'), ('manager', 'Manager: Read/Write'), ('viewer', 'Guest: Read only')], default='guest', max_length=20),
        ),
    ]
