# Generated by Django 5.1.5 on 2025-03-20 01:21

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppFW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deny', models.JSONField(default=list)),
                ('allow', models.JSONField(default=list)),
                ('precedence', models.CharField(choices=[('deny', 'Deny'), ('allow', 'Allow')], max_length=16)),
                ('nyu_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('init', 'Init Container'), ('main', 'Main Container'), ('sidecar', 'Sidecar Container')], max_length=16)),
                ('image', models.TextField()),
                ('port', models.IntegerField(default=None, null=True)),
                ('port_protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default=None, max_length=16, null=True)),
                ('command', models.JSONField(default=list, null=True)),
                ('args', models.JSONField(default=list, null=True)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', core.model_fields.UUID7StringField(auto_created=True, default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
                ('connection_port', models.IntegerField()),
                ('connection_protocol', models.CharField(choices=[('http', 'Web app'), ('tcp', 'TCP on random port'), ('udp', 'UDP on random port')], max_length=16)),
                ('update_strategy', models.CharField(choices=[('rolling', 'Rolling'), ('recreate', 'Recreate')], default='recreate', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('creating', 'Resource is being created'), ('updating', 'Resource is being updated'), ('deleting', 'Resource is being deleted'), ('created', 'Resource is created'), ('active', 'Resource is live'), ('stopped', 'Resource is stopped'), ('error', 'Resource is in error'), ('zombie', 'Resource exists in database but in cluster'), ('orphan', 'Resource exists in cluster but not in database')], default='creating', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_tls', models.BooleanField(default=False)),
                ('rules', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IngressHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=253, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_replicas', models.IntegerField(default=1)),
                ('max_replicas', models.IntegerField(default=1)),
                ('scaleup_stb_window', models.IntegerField(default=0)),
                ('scaledown_stb_window', models.IntegerField(default=150)),
                ('scalers', models.JSONField(default=list)),
            ],
        ),
    ]
