# Generated by Django 5.1.5 on 2025-03-20 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container_apps', '0001_initial'),
        ('infra', '0001_initial'),
        ('secret_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='env_secret',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_env_secrets', to='secret_store.secret'),
        ),
        migrations.AddField(
            model_name='container',
            name='pull_secret',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_pull_secrets', to='secret_store.secret'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='containers',
            field=models.ManyToManyField(blank=True, to='container_apps.container'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='ip_rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='container_apps.appfw'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.namespace'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='volumes',
            field=models.ManyToManyField(blank=True, to='infra.volume'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='ingress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='container_apps.ingress'),
        ),
        migrations.AddField(
            model_name='ingress',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='container_apps.ingresshosts'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='scaler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='container_apps.scaler'),
        ),
    ]
