# Generated by Django 5.0.7 on 2024-10-31 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container_apps', '0001_initial'),
        ('k8s', '0001_initial'),
        ('secret_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='env_secret',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_env_secrets', to='secret_store.secret'),
        ),
        migrations.AddField(
            model_name='container',
            name='pull_secret',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_pull_secrets', to='secret_store.secret'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='containers',
            field=models.ManyToManyField(blank=True, to='container_apps.container'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k8s.namespace'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='pvcs',
            field=models.ManyToManyField(blank=True, to='k8s.pvc'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='custom_domains',
            field=models.ManyToManyField(blank=True, to='container_apps.customdomain'),
        ),
        migrations.AddField(
            model_name='containerapp',
            name='hpa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='container_apps.hpa'),
        ),
    ]
