# Generated by Django 5.0.7 on 2024-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_apps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='cpu_request',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='memory_limit',
            field=models.FloatField(),
        ),
    ]
