# Generated by Django 5.0.7 on 2024-07-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=320, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NYUUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('netid', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
            ],
        ),
    ]
