# Generated by Django 5.0.7 on 2024-10-04 22:01

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRegistry',
            fields=[
                ('crid', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=32)),
                ('password', encrypted_model_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'container_registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
