# Generated by Django 5.0.7 on 2024-12-30 21:07

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crid', core.model_fields.UUID7StringField(default=core.model_fields.generate_uuid7, max_length=36, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('repo', models.SlugField()),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('creating', 'Resource is being created'), ('updating', 'Resource is being updated'), ('deleting', 'Resource is being deleted'), ('active', 'Resource is live'), ('stopped', 'Resource is stopped'), ('error', 'Resource is in error'), ('zombie', 'Resource exists in database but in cluster'), ('orphan', 'Resource exists in cluster but not in database')], default='creating', max_length=16)),
            ],
            options={
                'db_table': 'container_registry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('action', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
