# Generated by Django 5.0.7 on 2024-10-31 15:19

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRegistry',
            fields=[
                ('crid', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=32)),
                ('public', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=32)),
                ('password', encrypted_model_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('creating', 'Resource is being created'), ('updating', 'Resource is being updated'), ('deleting', 'Resource is being deleted'), ('active', 'Resource is live'), ('stopped', 'Resource is stopped'), ('error', 'Resource is in error'), ('zombie', 'Resource exists in database but in cluster')], default='creating', max_length=16)),
            ],
            options={
                'db_table': 'container_registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
