# Generated by Django 5.0.7 on 2024-10-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_registry', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerregistry',
            old_name='nsid',
            new_name='namespace',
        ),
    ]
