# Generated by Django 5.0.7 on 2024-10-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_registry', '0003_rename_nsid_containerregistry_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
