# Generated by Django 5.0.7 on 2024-10-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_registry', '0004_containerregistry_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerregistry',
            name='url',
        ),
        migrations.AddField(
            model_name='containerregistry',
            name='slug',
            field=models.SlugField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
