apiVersion: v1
kind: Service
metadata:
  labels:
    svc: osiris-cloud-prod
  name: osiris-cloud-prod-svc
  namespace: osiris-cloud
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: osiris-cloud
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
